<a href="https://colab.research.google.com/github/jillzhan1997/107-2Multimedia/blob/master/class2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
#https://zh.wilipedia.org/wiki/NumPy

In [0]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [0]:
y=np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a=np.array([1,3,6,9,])
b=np.linspace(0,15,4)
a,b

(array([1, 3, 6, 9]), array([ 0.,  5., 10., 15.]))

In [0]:
c=a-b
c

array([ 1., -2., -4., -6.])

In [0]:
a**2

array([ 1,  9, 36, 81])

In [0]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.transpose () 

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [0]:
a2=np.array([[1., 2.], [3., 4.]])
np.linalg.inv(a2)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [0]:
a3=np.array([[3,1],[1,2]])
b=np.array([9,8])
x=np.linalg.solve (a3 , b)
x

array([2., 3.])

In [0]:
c=np.random.rand(3,3)
c

array([[0.42269502, 0.56942798, 0.35652961],
       [0.83439351, 0.43391175, 0.95752573],
       [0.1810063 , 0.78872114, 0.32077761]])

In [0]:
np.dot(a,c)

array([[ 2.63450093,  3.80341488,  3.2339139 ],
       [ 6.94878541,  9.17959747,  8.13841274],
       [11.26306989, 14.55578006, 13.04291159]])

In [0]:
z=np.zeros((2,4),np.uint8)
type(z)

numpy.ndarray

In [0]:
z

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [0]:
o=np.ones ((2,4),np.int32)
o

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [0]:
m=np.array([[4,12,3,1],[10,12,14,29]],np.float32)
m

array([[ 4., 12.,  3.,  1.],
       [10., 12., 14., 29.]], dtype=float32)

In [0]:
m.shape

(2, 4)

In [0]:
m.dtype

dtype('float32')

In [0]:
m=np.array([[[1,2,3,4],[5,6,7,8]],[[10,11,12,14],[15,16,17,18]]],np.float32)
m

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[10., 11., 12., 14.],
        [15., 16., 17., 18.]]], dtype=float32)

In [0]:
m=np.array([[14,12,3,1],[10,12,114,29],[67,23,534,2]],np.float32)
m [1,3] 

29.0

In [0]:
m [2, :] 

array([ 67.,  23., 534.,   2.], dtype=float32)

In [0]:
m [:,3] 

array([ 1., 29.,  2.], dtype=float32)

In [0]:
m[0:2,1:3] 

array([[ 12.,   3.],
       [ 12., 114.]], dtype=float32)

In [0]:
m=np.array([[[1,2,3,4],[5,6,7,8]],[[10,11,12,14],[15,16,17,18]],[[11,12,43,32],[1,5, 10,23]
m

SyntaxError: invalid syntax (<ipython-input-137-6b1dd31bd784>, line 2)

In [0]:
m[:,:,0]

IndexError: too many indices for array

In [0]:
m[0,:,:]

IndexError: too many indices for array

In [0]:
src1=np.array([[23,123,90],[100,250,0]],np.uint8)
src2=np.array([[125,150,60],[100,10,40]],np.uint8)
dst=src1=src2
dst

array([[125, 150,  60],
       [100,  10,  40]], dtype=uint8)

In [0]:
src2=np.array([[125,150,60],[100,10,40]],np.float32)
dst=src1+src2
dst

array([[250., 300., 120.],
       [200.,  20.,  80.]], dtype=float32)

In [0]:
import cv2
dst=cv2.add (src1,  src2, dtype=cv2.CV_32F) 
dst

array([[250., 300., 120.],
       [200.,  20.,  80.]], dtype=float32)

In [0]:
src2=np.array([[125,150,60],[100,10,40]],np.uint8)
dst=src1-src2
dst

array([[0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [0]:
src2=np.array([[125,150,60],[100,10,40]],np.float32)
dst=src1*src2
dst

array([[15625., 22500.,  3600.],
       [10000.,   100.,  1600.]], dtype=float32)

In [0]:
dst=np.multiply (src1,src2) 
dst

array([[15625., 22500.,  3600.],
       [10000.,   100.,  1600.]], dtype=float32)

In [0]:
src2=np.array([[125,150,60],[100,10,40]],np.uint8)
dst=src2/src1
dst

array([[1., 1., 1.],
       [1., 1., 1.]])

In [0]:
src2=np.array([[125,150,60],[100,10,40]],np.float32)
dst=src2/src1
dst

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [0]:
src3=np.array([[1,2,3],[4,5,6]],np.uint8)
src4=np.array([[6,5],[4,3],[2,1]],np.uint8)
dst=np.dot(src3, src4)
dst

array([[20, 14],
       [56, 41]], dtype=uint8)

In [0]:
src5=np.array([[6,5],[4,3]],np.uint8)
dst2=np.log(src5)
dst2.dtype

dtype('float16')

In [0]:
dst2

array([[1.792, 1.609],
       [1.387, 1.099]], dtype=float16)

In [0]:
src=np.array([[30,40],[10,100]],np.uint8)
dst1=np.power(src,2)
dst1

array([[132,  64],
       [100,  16]], dtype=uint8)

In [0]:
dst2=np.power(src,2.0)
dst2

array([[  900.,  1600.],
       [  100., 10000.]])

In [0]:
dst2.dtype

dtype('float64')